### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by hommyshop** [wirecard/shopify-ee#4]
We have just integrated the plugin. The checkout's SSL is broken.

![screenshot-2019-04-12:15:17:13](https://user-images.githubusercontent.com/49198848/56036918-bc489000-5d36-11e9-9c66-07370ed35f4b.png)

This error might be related to an image being sent over http
![image](https://user-images.githubusercontent.com/49198848/56036780-6673e800-5d36-11e9-9e46-2b0c1d933654.png)

**Comment by jakubpolomsky** [comment]
The sources were all changed to ssl. Thank you for reporting!
