### ISSUE TITLE
missing ID in transactions

### ISSUE THREAD

**Issue by hommyshop** [wirecard/shopify-ee#6]
We've got several live transactions. I noticed that some of them have missing transaction IDs on Shopify's side. This problem makes it very difficult to track which transaction it is on Wirecard's side. Included 2 screenshots from 2 different customer orders. 1 of them has all IDs the other one doesn't have any.

No IDs on this one:
![noIds](https://user-images.githubusercontent.com/49198848/56078218-3d169300-5dee-11e9-8ff5-7332018343fc.png)

All IDs on this one:
![hasIds](https://user-images.githubusercontent.com/49198848/56078219-3d169300-5dee-11e9-8174-41b72365d758.png)

**Comment by jakubpolomsky** [comment]
Thank you for reporting this issue. It has been fixed and tested.

Kind regards
